Metatavu/mikkeli-theme

- functions.php
> Fixed issue #5

- css/layout.css
- header.php
- sass/_navigation.scss
- sass/features/_hero.scss
- sass/views/_sidebar.scss
- ReadSpeaker changed to be last item in header
- Mobile Menu: Map and Language aligned to center
- Sidebar: Current page item arrow changed to point up
> Mobile Menu CSS, ReadSpeaker, Sidebar Menu CSS

- css/layout.css
- sass/features/_blocks.scss
- sass/views/_sidebar.scss
- search.php
- Search: Publish date removed from all except post types
- SPTV: List line height and margins fixed
- Sidebar arrow buttons fixed to show right arrow image when in sub page
> Havaintoja 7.9. fixlist

- page.php
Page title removed from template if content with sidebar.
> Page Title with Sidebar Block

- css/layout.css
- page.php
- sass/views/_sidebar.scss
- Sidebar "open" arrow fix
- Page title and background-color change if page has own custom field settings
> Sidebar arrow-open and Page title + bgcolor

- css/layout.css
- sass/_config.scss
- sass/_wpdefaults.scss
- sass/views/_page.scss
- sass/views/_sidebar.scss
- Sidebar arrows fixed
- Table cells CSS
- Content links CSS
- Container width increased to 1200px
> Fixlist 13 10 2022

- header.php
Checking whether functions pll_current_language and pll_home_url exists before attemping to use them
> Added checks for pll functions

- sptv/components/mikkeli-common.php
- sptv/components/service_location_service_channel/phone-numbers.php
> Fixed issue with subsequent opening hours

- css/layout.css
> Changed the location of cookie consent accept button

- etusivu-tpl.php
- functions.php
> Fixed timezone in index page announcements

- css/layout.css
- header.php
> Added check whether pll_e function exists on the header.php

- sptv/components/mikkeli-common.php
> Changed theme to render opening hours ithout days correctly

- sptv/components/mikkeli-common.php
> Added support for displaying exception date ranges

- etusivu-tpl.php
> Added support for rendering content in a localized front page

- css/layout.css
- etusivu-tpl.php
- sidebar.php
- style.css
> Theme localization improvements

- css/layout.css
- etusivu-tpl.php
- functions.php
- searchform.php
- sidebar.php
- template-parts/blocks/banners/banners.php
> Feature 59 fontawesome replacement

- css/layout.css
> styled search bar to be shorter on desktop view

- css/layout.css
- style.css
> Smaller gap between main nav li elements

- header.php
> added scripts for google tag manager

- header.php
> Change chatbot

- header.php
> New map link, fixes on mobile links
